### ISSUE TITLE
As a mentor I need to see and review your works in week stages

### ISSUE THREAD

**Issue by zacck-zz** [WanjikuMac/Little-Kidogo-Apprenticeship#1]
### Expected Result 
Every week as a mentor, I need to go through the work you as a student has done for the week we can make this work better by committing work you have done on a branch so that the review can start reviews earlier and be done for the week.
In the end every week's work should be done on a different branch and merged into the master

**Comment by WanjikuMac** [comment]
Week two assignment has been committed under new branch

**Comment by zacck-zz** [comment]
@WanjikuMac  you can always reopen this issue until the work is merged

**Comment by zacck-zz** [comment]
@WanjikuMac closing this now as the PRs have been merged
